version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./docker/apache.conf:/etc/apache2/sites-available/server.conf:ro
      - ./docker/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php.dev.ini:/usr/local/etc/php/conf.d/development.ini:ro
      - ./:/app
    ports:
      - 8080:80

  coverage:
    image: m3ng9i/ran
    volumes:
      - ./coverage:/web:ro
    ports:
      - 8180:8080
